// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snake_Royale_Server.Models;

#nullable disable

namespace Snake_Royale_Server.Migrations
{
    [DbContext(typeof(SnakeRoyaleDbContext))]
    partial class SnakeRoyaleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Snake_Royale_Server.Models.Account", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("GamePlayed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
